### ISSUE TITLE
`npx hardhat node` doesn't set headers correctly when forking sepolia

### ISSUE THREAD

**Issue by MarcBickel** [NomicFoundation/edr#356]
### Version of Hardhat

2.22.2

### What happened?

When forking the sepolia network with `npx hardhat node --fork https://eth-sepolia.g.alchemy.com/v2/<key>` to test some custom scripts when I deploy a contract and perform a series of txs on it, I hit an error: 
```
thread 'tokio-runtime-worker' panicked at /Users/runner/work/hardhat/hardhat/crates/edr_evm/src/transaction.rs:45:18:
internal error: entered unreachable code: error: Header(ExcessBlobGasNotSet)
```

From what I understand, it seems like some headers needed since the cancun hardfork are not set properly. I believe the problem lies in the forking mechanism, because running the script either on sepolia directly works, or with anvil from Foundry (equivalent of `hardhat node` as far as I know) also works. 

The other header related to blob gas might also not be set. 

### Minimal reproduction steps

1. Fork sepolia with an Alchemy API key with `npx hardhat node --fork https://eth-sepolia.g.alchemy.com/v2/<key>`
2. create a TS script that uses `await ethers.getContractAt("IERC20", baseCurrencyContract);` and `const baseCurrencyContract = "0xaa8e23fb1079ea71e0a56f48a2aa51851d8433d0";` (just a testnetERC20 that I use for tests)
3. try to call a read function in this contract such as `contract.decimals()`
4. run the script with `npx hardhat run --network localhost scriptname`
5. get error

**Comment by d3mage** [comment]
+1

**Comment by Wodann** [comment]
We released [EDR v0.3.5](https://www.npmjs.com/package/@nomicfoundation/edr/v/0.3.5) with a fix for this issue.

If you’re using the latest Hardhat release, in order to use EDR v0.3.5, you can remove your `node_modules` directory and npm/yarn/pnpm lock file and reinstall your dependencies. You can verify that you’re using the correct version of EDR by running the following command: 

`npm ls @nomicfoundation/edr `

It should print `0.3.5`.

**Comment by cinnabarhorse** [comment]
Still getting this error with Hardhat 2.22.3 and edr version 0.3.7, even after deleting node_modules, cache, and all other possible dependencies. 

`thread 'tokio-runtime-worker' panicked at /Users/runner/work/edr/edr/crates/edr_evm/src/transaction.rs:48:18:`

Note: Was previously experiencing another issue with the "no known hardfork activation" on Polygon, but sorted that by adding this code in hardhat config:

``` chains: {
        137: {
          hardforkHistory: {
            cancun: 54876000,
          },
        },
      },```

However, after doing that the error above started appearing, so still unable to run scripts on forked Polygon mainnet.
